#!/usr/bin/env node

/**
 * Axiom Setup Wizard
 * Interactive setup for the Axiom AI Operating System.
 * Run: node setup.js
 *
 * Creates mythos.config.js, directory structure, and copies templates.
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { execSync } = require('child_process');

const AXIOM_ROOT = path.resolve(__dirname);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function ask(question, defaultVal) {
  return new Promise(resolve => {
    const suffix = defaultVal ? ` (${defaultVal})` : '';
    rl.question(`${question}${suffix}: `, answer => {
      resolve(answer.trim() || defaultVal || '');
    });
  });
}

async function detectGpu() {
  try {
    const raw = execSync('nvidia-smi --query-gpu=name,memory.total --format=csv,noheader', {
      encoding: 'utf8', timeout: 5000, windowsHide: true
    });
    const [name, mem] = raw.trim().split(',').map(s => s.trim());
    const vramMB = parseInt(mem);
    return { detected: true, name, vramMB };
  } catch {
    return { detected: false, name: 'none', vramMB: 0 };
  }
}

async function detectOllamaModels() {
  try {
    const raw = execSync('curl -s http://127.0.0.1:11434/api/tags', {
      encoding: 'utf8', timeout: 3000, windowsHide: true
    });
    const data = JSON.parse(raw);
    return (data.models || []).map(m => m.name);
  } catch {
    return [];
  }
}

async function run() {
  console.log('');
  console.log('  ╔═══════════════════════════════════════╗');
  console.log('  ║   AXIOM — Self-Improving AI OS        ║');
  console.log('  ║   Setup Wizard                        ║');
  console.log('  ╚═══════════════════════════════════════╝');
  console.log('');

  // 1. Install directory
  const installDir = await ask('Install directory', AXIOM_ROOT);

  // 2. GPU detection
  console.log('\nDetecting GPU...');
  const gpu = await detectGpu();
  let vramMB = 0;
  let gpuModel = 'none';

  if (gpu.detected) {
    console.log(`  Found: ${gpu.name} (${gpu.vramMB} MB VRAM)`);
    gpuModel = gpu.name;
    vramMB = gpu.vramMB;
  } else {
    console.log('  No NVIDIA GPU detected.');
    const manual = await ask('Enter GPU VRAM in MB (0 for no GPU)', '0');
    vramMB = parseInt(manual) || 0;
  }

  // 3. Ollama detection
  console.log('\nDetecting Ollama models...');
  const models = await detectOllamaModels();
  if (models.length > 0) {
    console.log(`  Found ${models.length} model(s): ${models.slice(0, 5).join(', ')}${models.length > 5 ? '...' : ''}`);
  } else {
    console.log('  Ollama not running or no models loaded.');
  }

  // 4. User info
  console.log('');
  const userName = await ask('Your name', '');
  const userRole = await ask('Your role (e.g., "Full-stack developer", "SaaS builder")', 'Developer');

  // 5. Projects
  console.log('\nProjects (press Enter with empty name to finish):');
  const projects = {};
  let i = 1;
  while (true) {
    const name = await ask(`  Project ${i} name`, '');
    if (!name) break;
    const codePath = await ask(`  Project ${i} code path`, '');
    projects[name] = { codePath: codePath || null };
    i++;
  }

  // 6. Backup directory
  const backupDir = await ask('\nBackup directory', path.join(installDir, 'backups'));

  // 7. Write config
  const config = {
    paths: {
      root: installDir,
      wiki: path.join(installDir, 'wiki'),
      skills: path.join(installDir, 'skills'),
      workspace: path.join(installDir, 'workspace'),
      queue: path.join(installDir, 'queue'),
      backups: backupDir,
    },
    hardware: {
      vramMB,
      ramHeadroomMB: 4096,
      gpuModel,
    },
    projects,
    user: {
      name: userName,
      role: userRole,
    },
    ollamaUrl: 'http://127.0.0.1:11434',
  };

  const configPath = path.join(installDir, 'mythos.config.js');
  const configContent = `// Axiom Configuration — Generated by setup wizard\nmodule.exports = ${JSON.stringify(config, null, 2)};\n`;
  fs.writeFileSync(configPath, configContent, 'utf8');
  console.log(`\nConfig written: ${configPath}`);

  // 8. Create directories
  const dirs = [
    config.paths.wiki,
    path.join(config.paths.wiki, '_system'),
    path.join(config.paths.wiki, '_staging', 'pending'),
    path.join(config.paths.wiki, '_staging', 'approved'),
    path.join(config.paths.wiki, '_staging', 'rejected'),
    config.paths.skills,
    config.paths.workspace,
    path.join(config.paths.workspace, 'briefs'),
    config.paths.queue,
    config.paths.backups,
  ];

  for (const dir of dirs) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      console.log(`  Created: ${dir}`);
    }
  }

  // 9. Copy templates
  const templatesDir = path.join(__dirname, 'templates');
  const wikiTemplateDir = path.join(__dirname, 'wiki-template');

  if (fs.existsSync(templatesDir)) {
    for (const file of fs.readdirSync(templatesDir)) {
      const src = path.join(templatesDir, file);
      const dest = path.join(installDir, file);
      if (!fs.existsSync(dest)) {
        fs.copyFileSync(src, dest);
        console.log(`  Copied: ${file}`);
      }
    }
  }

  if (fs.existsSync(wikiTemplateDir)) {
    copyDirRecursive(wikiTemplateDir, config.paths.wiki);
    console.log('  Copied wiki templates');
  }

  // 10. User identity in wiki
  const soulPath = path.join(config.paths.wiki, '_system', 'SOUL.md');
  if (!fs.existsSync(soulPath) && userName) {
    const soul = `---\ntitle: Identity\nwiki: system\nupdated: ${new Date().toISOString().split('T')[0]}\n---\n\n# Identity\n\nOwner: ${userName}\nRole: ${userRole}\n\n## Operating Principles\n\n- Ship fast, ship clean\n- Revenue lens on every output\n- Security first\n- No fluff\n`;
    fs.writeFileSync(soulPath, soul, 'utf8');
    console.log('  Created: _system/SOUL.md');
  }

  console.log('\n  ══════════════════════════════════════');
  console.log('  Axiom is ready.');
  console.log('');
  console.log('  Next steps:');
  console.log('    node core/system-audit.js     — run system health check');
  console.log('    node core/skill-registry.js scan — index your skills');
  console.log('    node core/knowledge-accelerator.js — see research domains');
  console.log('  ══════════════════════════════════════');
  console.log('');

  rl.close();
}

function copyDirRecursive(src, dest) {
  if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src)) {
    const srcPath = path.join(src, entry);
    const destPath = path.join(dest, entry);
    if (fs.statSync(srcPath).isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else if (!fs.existsSync(destPath)) {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

run().catch(err => {
  console.error('Setup failed:', err.message);
  rl.close();
  process.exit(1);
});
